name: veggie_track
description: An app to follow your meat consumption for every meals

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.11
  color: ^3.0.0
  intl: ^0.18.0
  meta:
  isar_veggie_track:
    path: packages/isar_veggie_track
  veggie_track_repository:
    path: packages/veggie_track_repository
  pocketbase_veggie_track:
    path: packages/pocketbase_veggie_track


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  adaptive_icon_background: "#2f3631"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true


flutter:
  uses-material-design: true
    